name: deerfold_venv
channels:
  - pytorch  # Prioritize pytorch channel for PyTorch and CUDA compatibility
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - setuptools=59.5.0
  - pip
  - openmm=7.5.1
  - pdbfixer
  - aria2
  - hmmer=3.3.2
  - hhsuite=3.3.0
  - kalign2=2.04
  - matplotlib=3.5.3
  - pytorch=1.13.0 
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - pytorch-cuda=11.7
  - mkl=2024.0
  - pip:
      - pandas==1.3.5
      - biopython==1.79
      - deepspeed==0.5.10
      - dm-tree==0.1.6
      - ml-collections==0.1.0
      - numpy==1.21.5
      - PyYAML==5.4.1
      - requests==2.26.0
      - scipy==1.7.1
      - tqdm==4.62.2
      - typing-extensions==3.10.0.2
      - pytorch_lightning==1.5.0
      - wandb==0.12.21
      - git+https://github.com/NVIDIA/dllogger.git